name: Citizen Registry CI Pipeline

on:
  push:
    branches:
      - 'feature/*'  # Trigger only on thematic branches (e.g., feature/*)
  pull_request:
    branches:
      - develop      # Optional: Allow PR validation for develop

jobs:
  checkout:
    name: Check Out Repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: mvn test -Dtest='*UnitTest'

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Integration Tests
        run: mvn test -Dtest='*IntegrationTest'

  merge:
    name: Merge Thematic Branch into Develop
    runs-on: ubuntu-latest
    needs: integration-tests
    if: ${{ success() }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Merge Thematic Branch
        run: |
          git checkout develop
          git merge ${{ github.ref_name }}
          git push origin develop